[tox]
requires =
    tox>=4
envlist = clean, format, lint, typecheck, py3.11, py3.12, py3.13, py3.14, report

[testenv]
usedevelop = true
deps = -r requirements_dev.txt
set_env =
    py3.{11,12,13,14}: COVERAGE_FILE = .coverage.{envname}

[testenv:clean]
description = Run pyclean
skip_install = true
deps = pyclean
commands = pyclean . --debris

[testenv:format]
description = Run black code formatter
skip_install = true
deps = black
depends = clean
commands = black -v {posargs: src/ tests/}

[testenv:lint]
description = Run flake8 linter
skip_install = true
deps = flake8
depends = clean
commands = flake8 -v {posargs: src/ tests/}

[testenv:typecheck]
description = Run mypy type checker
skip_install = true
deps = mypy
depends = clean
commands = mypy {posargs: src/kvpexpand}

[testenv:py3.11]
description = Run unit tests for Python 3.11
depends = clean, format, lint, typecheck
commands = 
    coverage erase
    coverage run --data-file .coverage.py3.11 {posargs: -m unittest}

[testenv:py3.12]
description = Run unit tests for Python 3.12
depends = clean, format, lint, typecheck
commands = 
    coverage erase
    coverage run --data-file .coverage.py3.12 {posargs: -m unittest}

[testenv:py3.13]
description = Run unit tests for Python 3.13
depends = clean, format, lint, typecheck
commands = 
    coverage erase
    coverage run --data-file .coverage.py3.13 {posargs: -m unittest}

[testenv:py3.14]
description = Run unit tests for Python 3.14
depends = clean, format, lint, typecheck
commands = 
    coverage erase
    coverage run --data-file .coverage.py3.14 {posargs: -m unittest}

[testenv:report]
description = Generate coverage report
skip_install = true
deps = coverage
depends = py3.11, py3.12, py3.13, py3.14
commands = 
    coverage combine
    coverage report
    coverage html
    coverage erase

[flake8]
show-source = true
max-line-length = 88
extend-ignore = E203 W503